separateAo = true

sliders = shadowMapResolution SHADOW_DISTORT_FACTOR ambientOcclusionLevel sunPathRotation ROUGHNESS_EXPONENT
screen = ENABLE_SHADOWS shadowMapResolution ENABLE_SHADOW_DISTORT SHADOW_DISTORT_FACTOR ambientOcclusionLevel sunPathRotation DISABLE_BLOCK_LIGHT_TINT [MATERIALS]
screen.MATERIALS = ROUGHNESS_EXPONENT

iris.features.optional=FADE_VARIABLE
